invalid_email:
  code: 1001
  localization:
    en: "Email is invalid. Please try again."
    th: "รูปแบบอีเมลไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

# These are what we response to our internal services
internal:
  success:
    code: 0
    localization:
      en: "Success"
      th: "สำเร็จ"

  general:
    code: 500
    localization:
      en: "System cannot process this request at the moment. Please try again later"
      th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"

  bad_request:
    code: 400
    localization:
      en: "System cannot process this request at the moment. Please try again later"
      th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"

  connection_error:
    code: 500
    localization:
      en: "Connection error. Please try again"
      th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"

  database_not_found:
    code: 404
    localization:
      en: "Database not found. Please try again"
      th: "ขออภัย ไม่พบข้อมูลในระบบ กรุณาลองใหม่อีกครั้ง"

  unauthorized:
    code: 401
    localization:
      en: "The system does not allow you to access the request. Please try again later"
      th: "ขออภัย ระบบไม่อนุญาตให้คุณเข้าถึงการร้องขอได้ กรุณาลองใหม่อีกครั้ง"
